#!/bin/bash
#
#  Copyright (c) 2024-2025, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#MIME_PATTERN="application/x-executable"
#DIR_LIST="cli","ncp"

set -exo pipefail

OT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET-}
BUILD_DIR="${OT_CMAKE_BUILD_DIR:-build_mcxw72}"

readonly OT_SRCDIR="$(pwd)"
readonly OT_OPTIONS=(
    "-DBUILD_TESTING=OFF"
    "-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
    "-DCMAKE_BUILD_TYPE=MinSizeRel"
    "-DOT_NXP_EXPORT_TO_SREC=ON"
    "-DOT_PLATFORM=external"
    "-DOT_SLAAC=ON"
    "-DOT_NXP_PLATFORM_FAMILY=mcxw"
    "-DOT_NXP_PLATFORM=mcxw72"
)

readonly OT_OPTIONS_NO_RCP=(
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_RCP=OFF"
    "-DOT_MAC_CSL_RECEIVER_ENABLE=ON"
    "-DOT_APP_LOWPOWER=ON"
    "-DOT_NXP_NVS=ON"
)

readonly OT_OPTIONS_RCP=(
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=ON"
    "-DOT_RCP=ON"
    "-DOT_NCP_SPI=ON"
    "-DOT_MAC_CSL_RECEIVER_ENABLE=ON"
    "-DOT_APP_LOWPOWER=ON"
    "-DOT_NXP_NVS=ON"
)

readonly OT_OPTIONS_CLI_FTD_BLE_SHELL=(
    "-DOT_NCP_SPI=OFF"
    "-DOT_APP_CLI=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_APP_NCP=OFF"
    "-DOT_FTD=ON"
    "-DOT_MTD=OFF"
    "-DOT_BLE_SUPPORT=ON"
    "-DOT_APP_FTD_BLE_SHELL=ON"
    "-DOT_PING_SENDER=ON"
    "-DOT_APP_LOWPOWER=OFF"
    "-DCONF_FILE=${OT_SRCDIR}/examples/hybrid/ot_cli_ftd_ble_shell/prj.conf"
)

readonly OT_OPTIONS_CLI_NVS=(
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_RCP=OFF"
    "-DOT_MAC_CSL_RECEIVER_ENABLE=ON"
    "-DOT_APP_LOWPOWER=ON"
    "-DOT_NXP_NVS=ON"
)

# Add this function after the readonly declarations
get_conf_file_for_build() {
    local build_options=("$@")
    local nvs_status="missing"  # Can be "on", "off", or "missing"

    # Check if NVS is enabled in the build options
    for option in "${build_options[@]}"; do
        if [[ "$option" == "-DOT_NXP_NVS=ON" ]]; then
            nvs_status="on"
            break
        elif [[ "$option" == "-DOT_NXP_NVS=OFF" ]]; then
            nvs_status="off"
            break
        fi
    done

    if [[ "$nvs_status" == "on" ]]; then
        echo "-DCONF_FILE=${OT_SRCDIR}/src/mcxw/platform/prj_nvs.conf"
    elif [[ "$nvs_status" == "off" ]]; then
        echo "-DCONF_FILE=${OT_SRCDIR}/src/mcxw/platform/prj_nvm.conf"
    fi
}

build()
{
    local cmakeArgs=("${@}")

    if [ ! "$1" = "folder_not_specified" ]; then
        cmakeArgs=("${@:2}")
        rcp_folder_name="/$1"
    fi

    # Add conditional CONF_FILE based on NVS setting
    local conf_file_option=$(get_conf_file_for_build "${cmakeArgs[@]}")
    cmakeArgs+=("$conf_file_option")

    # shellcheck disable=SC2068
    west build -d "${BUILD_DIR}${rcp_folder_name}" --config release -b frdmmcxw72 . --no_sanity_check -Dcore_id=cm33_core0 -DSDK_GH=$SDK_GH -DUSE_NBU=1 -DFPGA_BUILD=0 -DOT_COMPILE_WARNING_AS_ERROR=ON ${cmakeArgs[@]}
}

build_ot_without_rcp_image()
{
    echo "Building OT without RCP image ..."
    app_folder_name="folder_not_specified"
    local options=("${app_folder_name}")
    options+=("${OT_OPTIONS_NO_RCP[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("$@")

    options+=(" -DSDK_RELEASE=$SDK_RELEASE")

    build "${options[@]}"

    if [ $? -eq 1 ]; then
        exit 1
    fi
}

build_ot_with_rcp_image()
{
    echo "Building OT with RCP image ..."
    app_folder_name="rcp_bin"
    local options=("${app_folder_name}")
    options+=("${OT_OPTIONS_RCP[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("$@")

    options+=(" -DSDK_RELEASE=$SDK_RELEASE")

    build "${options[@]}"

    if [ $? -eq 1 ]; then
        exit 1
    fi
}

build_ot_cli_ftd_ble_shell()
{
    echo "Building dual mode app OT CLI FTD + BLE_shell ..."
    app_folder_name="ot_cli_ftd_ble_shell"
    local options=("${app_folder_name}")
    options+=("${OT_OPTIONS_CLI_FTD_BLE_SHELL[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("$@")
    options+=(" -DSDK_RELEASE=$SDK_RELEASE")
    build "${options[@]}"

    if [ $? -eq 1 ]; then
        exit 1
    fi
}

build_ot_cli_nvs()
{
    echo "Building OT CLI with NVS support ..."
    app_folder_name="ot_cli_nvs"
    local options=("${app_folder_name}")
    options+=("${OT_OPTIONS_CLI_NVS[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("$@")
    options+=(" -DSDK_RELEASE=$SDK_RELEASE")
    build "${options[@]}"

    if [ $? -eq 1 ]; then
        exit 1
    fi
}

create_directory_and_build()
{
    if [ "$1" == 'all' ]; then
        build_ot_without_rcp_image "$@"
        build_ot_with_rcp_image "$@"
        build_ot_cli_ftd_ble_shell "$@"
        build_ot_cli_nvs "$@"
    elif [ "$1" == 'ot_without_rcp_image' ]; then
        build_ot_without_rcp_image "$@"
    elif [ "$1" == 'ot_cli_ftd_ble_shell' ]; then
        build_ot_cli_ftd_ble_shell "$@"
    elif [ "$1" == 'ot_cli_nvs' ]; then
        build_ot_cli_nvs "$@"
    else
        echo >&2 "Unsupported action: $1. Supported: all, ot_without_rcp_image, ot_cli_ftd_ble_shell, build_ot_cli_nvs"
        # 128 for Invalid arguments
        exit 128
    fi
}

main()
{
    SDK_GH=ON
    SDK_RELEASE=OFF

    if [ $# == 0 ]; then
        create_directory_and_build all $SDK_RELEASE "$@"
    else
        create_directory_and_build "$1" $SDK_RELEASE "$@"
    fi

}

main "$@"
